### ISSUE TITLE
Server?

### ISSUE THREAD

**Issue by jannnfe** [joshborup/drawthings.fun#1]
Hello,
We are currently working on a similar project at my university, but have problems working with socket.io. Our project should be a little more developed than theirs, with login, chat and guessing words.
We tried to set up your project locally on our computer. Unfortunately, we do not have the server-side component in their Github repository. React can be started, but the important side of the backend is only partially available, or are we wrong there?
We would like to get your project up and running locally, so it runs like it did on www.drawthings.fun.
We would love to hear from you.
Thanks! :)

**Comment by joshborup** [comment]
I have gone ahead and updated the README and some of the project files with more instructions on how to get up and running. If you are still having issues getting started let me know!

**Comment by jannnfe** [comment]
Thank you for your help! :)
